x-common-variables: &common-variables
  CLUSTER_ID: 'OUYyQUFBNEU5NkY0NDVBND'
  KAFKA_PROCESS_ROLES: 'broker,controller'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
  KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'

services:
  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: confluentinc/cp-kafka
    networks:
      default:
        aliases:
          - kafka
    ports:
      - "19092:19092"
    environment:
      <<: *common-variables
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:19092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://:9092,EXTERNAL://localhost:19092'
  kafka2:
    container_name: kafka2
    hostname: kafka2
    image: confluentinc/cp-kafka
    networks:
      default:
        aliases:
          - kafka
    ports:
      - "29092:29092"
    environment:
      <<: *common-variables
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:29092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://:9092,EXTERNAL://localhost:29092'
  kafka3:
    container_name: kafka3
    hostname: kafka3
    image: confluentinc/cp-kafka
    networks:
      default:
        aliases:
          - kafka
    ports:
      - "39092:39092"
    environment:
      <<: *common-variables
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: 'INTERNAL://:9092,EXTERNAL://:39092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://:9092,EXTERNAL://localhost:39092'
