x-common-variables: &common-variables
  CLUSTER_ID: 'OUYyQUFBNEU5NkY0NDVBND'
  KAFKA_PROCESS_ROLES: 'broker,controller'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:9093,2@kafka2:9093,3@kafka3:9093'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'INSIDE'
  KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,OUTSIDE:SASL_PLAINTEXT'
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
  KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
  KAFKA_SUPER_USERS: 'User:admin'
  KAFKA_AUTHORIZER_CLASS_NAME: 'org.apache.kafka.metadata.authorizer.StandardAuthorizer'
  KAFKA_OPTS: '-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf'
x-common-volumes: &common-volumes
  type: bind
  source: ./secrets
  target: /etc/kafka/secrets
services:
  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: confluentinc/cp-kafka:latest
    networks:
      default:
        aliases:
          - kafka
    ports:
      - "19092:39092"
    volumes:
      - *common-volumes
    environment:
      <<: *common-variables
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: 'INSIDE://:9092,CONTROLLER://:9093,OUTSIDE://:19092'
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://kafka1:9092,OUTSIDE://localhost:19092'
  kafka2:
    container_name: kafka2
    hostname: kafka2
    image: confluentinc/cp-kafka:latest
    networks:
      default:
        aliases:
          - kafka
    ports:
      - "29092:39092"
    volumes:
      - *common-volumes
    environment:
      <<: *common-variables
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: 'INSIDE://:9092,CONTROLLER://:9093,OUTSIDE://:29092'
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://kafka2:9092,OUTSIDE://localhost:29092'
  kafka3:
    container_name: kafka3
    hostname: kafka3
    image: confluentinc/cp-kafka:latest
    networks:
      default:
        aliases:
          - kafka
    ports:
      - "39092:39092"
    volumes:
      - *common-volumes
    environment:
      <<: *common-variables
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: 'INSIDE://:9092,CONTROLLER://:9093,OUTSIDE://:39092'
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://kafka3:9092,OUTSIDE://localhost:39092'
